### PR TITLE
Use an empty struct instead of nullptr_t to represent null.

### LINKED ISSUE #91: Json11 fails to build with clang 4.0.0
json11 fails to build with clang 4.0 likely due to llvm-mirror/clang@4b6ad14
```
% /usr/bin/clang -v
FreeBSD clang version 4.0.0 (branches/release_40 292009) (based on LLVM 4.0.0)
Target: x86_64-unknown-freebsd12.0
Thread model: posix
InstalledDir: /usr/bin
```
```
ext/json11/json11.cpp:153:24: error: invalid operands to binary expression
      ('nullptr_t' and 'nullptr_t')
        return m_value < static_cast<const Value<tag, T> *>(other)->m_value;
               ~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ext/json11/json11.cpp:209:5: note: in instantiation of member function
      'json11::Value<json11::Json::Type::NUL, nullptr_t>::less' requested here
    JsonNull() : Value(nullptr) {}
    ^
```

Also reported here: https://github.com/PowerDNS/pdns/issues/4913

### PR DESCRIPTION
**Pull request by j4cbo**
Fixes #91.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@j4cbo, it looks like you've already signed the Dropbox CLA. Thanks!
